In [1]:
import camera
from numpy import *
from PIL import Image
from pylab import *
from scipy import *

img1=Image.open('images/001.jpg')
figure()
imshow(img1)

In [11]:
import camera
from numpy import *
from PIL import Image
from pylab import *
from scipy import *

# load some images
im1 = array(Image.open('images/001.jpg'))
im2 = array(Image.open('images/002.jpg'))

# load 2D points for each view to a list
points2D = [loadtxt('2D/00'+str(i+1)+'.corners').T for i in range(3)]
print 'points 2D'; print points2D

# load 3D points
points3D = loadtxt('3D/p3d').T
print'Points 3D'; print points3D

# load correspondences
corr = genfromtxt('2D/nview-corners',dtype='int',missing_values='*')
print 'corr'; print corr

# load cameras to a list of Camera objects (ma tran P cua tung Camera)
P = [camera.Camera(loadtxt('2D/00'+str(i+1)+'.P')) for i in range(3)]
print 'P'; print P

points 2D
[array([[ 718.79 ,  676.587,  675.319, ...,  479.229,  475.771,  474.916],
       [ 263.096,  424.715,  394.656, ...,  441.16 ,  429.052,  419.315]]), array([[ 689.792,  688.621,  951.71 , ...,  470.376,  466.728,  466.172],
       [ 460.223,  428.371,  438.48 , ...,  475.694,  462.309,  452.315]]), array([[ 755.058,  969.715,  748.762, ...,  501.171,  497.93 ,  497.132],
       [ 302.399,  462.839,  125.158, ...,  501.598,  487.109,  478.137]])]
Points 3D
[[ 3.7585792   1.0378863   1.5606923  ...,  2.7471349   0.73672803
   0.97395698]
 [-0.44845037 -0.54627892 -0.5211711  ...,  1.4925585   0.6206597
   0.64403613]
 [ 4.4300374   3.4601538   3.4636809  ...,  0.00678837 -0.17002507
  -0.23360821]]
corr
[[  0  -1   0]
 [  1   0  -1]
 [  2   1  -1]
 ..., 
 [639 665 511]
 [640 666 512]
 [641 667 513]]
P
[<camera.Camera object at 0x0000000007D746D8>, <camera.Camera object at 0x00000000065BE8D0>, <camera.Camera object at 0x0000000009C756D8>]


In [15]:
import camera
from numpy import *
from PIL import Image
from pylab import *
from scipy import *

execfile('load_vggdata.py')

# make 3D points homogeneous and project
X = vstack( (points3D,ones(points3D.shape[1])) )
x = P[0].project(X)

# plotting the points in view 1
figure()
imshow(im1)
plot(points2D[0][0],points2D[0][1],'*')
axis('off')
figure()
imshow(im1)
plot(x[0],x[1],'r.')
axis('off')

(-0.5, 1023.5, 767.5, -0.5)